version: '3.9'

services:
  web:
    build:
      context: .
    container_name: fast_app
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/fastapp
      - media:/fastapp/src/media
    command: sh -c "sh scripts/start_app.sh"
    ports:
      - "8000:8000"

  db:
    image: postgres:16
    container_name: fastapp_db
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  media:
  db_data:
